-- 0015_worker_cron.sql
-- Drain do analysis-worker: agendado fora do Postgres (sem pg_cron/pg_net).
--
-- A versão anterior dependia de pg_cron + pg_net + Vault com URL hardcoded
-- no Vercel e current_setting('myapp.internal_key') nunca setado — quebrada
-- em banco zero. O drain passa a ser um Scheduled Task do Coolify:
--
--   schedule: */5 * * * *
--   command:
--     curl -fsS -X POST http://localhost:3000/api/analysis-worker \
--       -H "x-internal-api-key: $INTERNAL_API_KEY"
--
-- Alternativa aceita pelo route: Authorization: Bearer $CRON_SECRET.
--
-- Esta migration é um no-op documental para manter a cadeia 0001–0015
-- aplicável sem estender pg_cron/vault no Supabase self-hosted.
